remote_theme: just-the-docs/just-the-docs


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/archive.png"

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/ZWolken/Calc_Review"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

color_scheme: nopurple
